---
- name: Check for Kiali Operator install
  block:
    - name: Check for Subscription
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: kiali
        namespace: openshift-operators
      register: subscription_kiali

    - name: Get current installed CSV
      debug:
        var: subscription_kiali.resources.status.installedCSV 

    - name: Get CSV
      kubernetes.core.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        name: "{{ subscription_kiali.resources.status.installedCSV }}"
        namespace: openshift-operators
      register: csv_kiali

    - name: Get CSV Status
      ansible.builtin.assert:
        that:
          - "csv_kiali.resources.status.phase == 'Succeeded'"
